server:
  port: 16784

spring:
  application:
    name: drift-follow-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/drift?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: P@ssw0rd
      initial-size: 20
      min-idle: 20
      max-active: 140
      max-wait: 6000
      socket-timeout: 20000